---
- name: installing docker, pip, docker-compose and starting docker-deamon
  hosts: all #ec2
  gether_facts: False
  tasks:
  - name: Ensure ssh port is open
    wait_for:
      port: 22
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      delay: 10
      timeout: 100
      search_regex: OpenSSH
    vars:
      ansbile_connection: local
      ansible_python_interpreter: /usr/bin/python

- name: installing docker, pip, docker-compose and starting docker-deamon
  hosts: all #ec2
  become: yes
  tasks:
  - name: make sure docker, pip and docker-compose is installed and ensure docker-deamon is running.
    yum:
      name:
       - docker
       - python3
       - pip
      state: present
      update_cache: yes
  - name: downloading docker compose and install
    get_url:
        url: https://github.com/docker/compose/releases/download/1.29.0/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
  - name: ensure docker is running
    ansible.builtin.systemd:
        name: docker
        state: started

- name: python docker pkg installing
  hosts: all #ec2
  tasks:
  - name: python docker pkg installing
    pip:
      name: 
        - docker
        - docker-compose

- name: adding ec2-user in docker group
  hosts: all #ec2
  become: yes
  tasks:
  - name: adding ec2-user in docker group
    user:
      name: ec2-user
      groups: docker
      append: yes
  - name: Reconnectiong to server session
    meta: reset_connection

- name: Start Docker container
  hosts: all #ec2
  vars_files:
    - project_vars
  tasks:
    - name: copy docker compose
      ansible.builtin.copy:
        src: docker-compose-full.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Log into docker-hub private registry
      community.docker.docker_login:
        registry_url: https://index.docker.io/v1/
        username: faizalshikalgar
        password: "{{docker_password}}"
    - name: start docker container from compose
      community.docker.docker_compose:
        project_src: /home/ec2-user/
        state: present