---
- name: installing docker, pip, docker-compose and starting docker-deamon
  hosts: ec2
  become: yes
  tasks:
  - name: make sure docker, pip and docker-compose is installed and ensure docker-deamon is running.
    yum:
      name:
       - docker
       - python3
       - pip
       - python3-docker
      state: present
      update_cache: yes
  - name: downloading docker compose and install
    get_url:
        url: https://github.com/docker/compose/releases/download/1.29.0/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
  - name: ensure docker is running
    ansible.builtin.systemd:
        name: docker
        state: started

- name: python docker pkg installing
  hosts: ec2
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  - name: python docker pkg installing
    pip:
      name: 
        - docker
        - docker-compose

- name: creating new user
  hosts: ec2
  become: yes
  tasks:
  - name: creating new linux user
    user:
      name: faizal
      groups: adm,docker,faizal
      append: yes
  # - name: Reconnectiong to server session
  #   meta: reset_connection

- name: Start Docker container
  hosts: ec2
  become: yes
  become_user: faizal
  vars_files: 
    - project_vars
  tasks:
    - name: copy docker compose
      ansible.builtin.copy:
        src: docker-compose-full.yaml
        dest: /home/faizal/docker-compose.yaml
    - name: Log into docker-hub private registry
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: faizalshikalgar
        password: "{{docker_password}}"
    - name: start docker container from compose
      community.docker.docker_compose:
        project_src: /home/faizal/
        state: present